### ISSUE TITLE
部署 dev 分支 搭建完后创建V2ray节点，在用户的节点列表点开详细显示500错误，V2ray的订阅和连接也没法使用

### ISSUE THREAD

**Issue by fugood** [Anankke/SSPanel-Uim#1505]
![QQ截图20220713220921](https://user-images.githubusercontent.com/73930611/178754999-d8cf8b3f-d8ce-4e78-906f-23797ac28039.jpg)

**Comment by fugood** [comment]
添加V2ray节点后，没有在/storage/framework/smarty/compile目录下生成XXXXXXXXXXXX_0.file.node_v2ray.tpl.php文件，请问怎样解决？

**Comment by fugood** [comment]
随非是开发解决了，没春它办法了

**Comment by vagur1689** [comment]
这个问题已经好几个月了

**Comment by iamsaltedfish** [comment]
需要提供这些信息：

**Comment by linglala** [comment]
同样的问题，不解决！根本没办法用…

**Comment by linglala** [comment]
> 需要提供这些信息的内容： 1）地址栏的内容 2）json编辑器中的填写

节点配置的是vless，而V2ray下发的订阅那好像只支vmess，另外节点详情点开报错500

**Comment by iamsaltedfish** [comment]
修了 https://github.com/Anankke/SSPanel-Uim/pull/1510/files

**Comment by yangliuchang** [comment]
我也遇到了，不过我是trojan

Slim Application Error
The application could not run because of the following error:

Details
Type: TypeError
Message: App\Models\Node::getArgs(): Return value must be of type array, null returned
File: /www/wwwroot/jc.jsloli.com/src/Models/Node.php
Line: 266
Trace
#0 /www/wwwroot/jc.jsloli.com/src/Models/Node.php(428): App\Models\Node->getArgs()
#1 /www/wwwroot/jc.jsloli.com/src/Controllers/User/NodeController.php(170): App\Models\Node->getTrojanItem()
#2 [internal function]: App\Controllers\User\NodeController->userNodeInfo()
#3 /www/wwwroot/jc.jsloli.com/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func()
#4 /www/wwwroot/jc.jsloli.com/vendor/slim/slim/Slim/Route.php(344): Slim\Handlers\Strategies\RequestResponse->__invoke()
#5 /www/wwwroot/jc.jsloli.com/src/Middleware/Auth.php(21): Slim\Route->__invoke()
#6 [internal function]: App\Middleware\Auth->__invoke()
#7 /www/wwwroot/jc.jsloli.com/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array()
#8 [internal function]: Slim\DeferredCallable->__invoke()
#9 /www/wwwroot/jc.jsloli.com/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(67): call_user_func()
#10 /www/wwwroot/jc.jsloli.com/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(116): Slim\Route->Slim\{closure}()
#11 /www/wwwroot/jc.jsloli.com/vendor/slim/slim/Slim/Route.php(316): Slim\Route->callMiddlewareStack()
#12 /www/wwwroot/jc.jsloli.com/vendor/slim/slim/Slim/App.php(438): Slim\Route->run()
#13 /www/wwwroot/jc.jsloli.com/vendor/zeuxisoo/slim-whoops/src/Zeuxisoo/Whoops/Provider/Slim/WhoopsMiddleware.php(70): Slim\App->__invoke()
#14 [internal function]: Zeuxisoo\Whoops\Provider\Slim\WhoopsMiddleware->__invoke()
#15 /www/wwwroot/jc.jsloli.com/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array()
#16 [internal function]: Slim\DeferredCallable->__invoke()
#17 /www/wwwroot/jc.jsloli.com/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(67): call_user_func()
#18 /www/wwwroot/jc.jsloli.com/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(116): Slim\App->Slim\{closure}()
#19 /www/wwwroot/jc.jsloli.com/vendor/slim/slim/Slim/App.php(332): Slim\App->callMiddlewareStack()
#20 /www/wwwroot/jc.jsloli.com/vendor/slim/slim/Slim/App.php(293): Slim\App->process()
#21 /www/wwwroot/jc.jsloli.com/public/index.php(41): Slim\App->run()
#22 {main}
