### ISSUE TITLE
[BUG] 关于使用Shadowsocks协议发生的问题

### ISSUE THREAD

**Issue by AlphaEldon** [Anankke/SSPanel-Uim#2128]
OS:    CentOS Stream 9
PHP version:    PHP 8.2 with OPcache
DB version:    MariaDB 10.11
SSpanel-UIM版本: 2023.4

使用协议 Shadowsocks 中转端口在使用前端配置中无法正常订阅

在前端配置端口 与 '注册' 中的连接设置   如可设置单端口承载用户 可抛其一

前端节点进行中转配置后
通过clash订阅后 只会获取到 用户连接设置中的端口 前端配置的端口

或在前端配置中使用 "offset_port_user"："xxxx" ←端口与用户注册默认值中的连接设置一致，也会导致用户注册失败

**Comment by AlphaEldon** [comment]
?关闭是因为这个问题很低级吗

**Comment by M1Screw** [comment]
manyuser feature for Shadowsocks is never any part of the current Shadowsocks protocol and never will be, 3rd party server who claims they can do this is non-compliant with the standard and this thing will introduce performance issues because Shadowsocks is never designed to work on a single port(what a surprise), so yes, this is a stupid question.
