### ISSUE TITLE
[BUG] 当面付通道返利异常

### ISSUE THREAD

**Issue by reizhi** [Anankke/SSPanel-Uim#2336]
**Environment 环境**

OS:   Debian 12
HTTPS enabled: √   
PHP version:    8.3.1
DB version:  11.2.2-MariaDB
Redis version:    7.2.3
Commit:    aaf8e77f333f887aad3e8d753d9ad1dd96b613fa

**Bug Info**

通过当面付通道付款成功，一笔购买会触发多次返利。支付成功的当时会触发4次，后续大致在4分钟，10分钟……等时间会再次触发返利。与[支付宝异步通知](https://opendocs.alipay.com/open/194/103296)中通知失败重新发起通知的频率大致相同。

查看相关文档，通知应答需要为`success`。修改
```
            return $response->withJson([
                'ret' => 1,
                'msg' => '支付成功',
            ]);
```
为
```
            return $response->write('success');
```
问题解决

站点同时配置了易支付，无此问题。

**Comment by M1Screw** [comment]
This could be a rebate system bug because the same response/re-notify in the test environment won't trigger repeated rebate awards using Alipay F2F.

**Comment by M1Screw** [comment]
Well, it looks like the problem is way greater than I first thought, the whole rebate system needs some rework it seems.

The current system doesn't have any mechanics built in to prevent the behavior you described from happening, a single payment gateway misbehave shouldn't lead to rebate rewards being given out multiple times in the first place.

**Comment by M1Screw** [comment]
Reward service has been added at https://github.com/Anankke/SSPanel-Uim/commit/5ba50696f4a4d830aabebadc143f5a8c47f79ecd.
